name: GitHub BayCal test
run-name: ${{ github.actor }} is testing out BayCal
on: [push, pull_request]
jobs:
  Test-BayCal-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: cd .. && rm -Rf raven && git clone https://github.com/idaholab/raven.git
      # using branch for now
      - run: cd ../raven && git checkout -b wangc/update_libs remotes/origin/wangc/update_libs
      - run: python3 ../raven/scripts/install_plugins.py -s ${{ github.workspace }}
      - run: WD=`(cd ../../.. && pwd)` && export RAVEN_LIBS_NAME="raven_libs_"`basename $WD` && ../raven/scripts/establish_conda_env.sh --install
      - run: cd ../raven && ./build_raven
      - run: ../raven/run_tests --library-report
      - run: ../raven/run_tests -j4 --plugins --re=BayCal

